/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author sebte
 */
public class NBA_Bracket extends javax.swing.JFrame {

    /**
     * Creates new form NBA_Bracket
     */
    public NBA_Bracket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCTextField26 = new app.bolivia.swing.JCTextField();
        jCTextField27 = new app.bolivia.swing.JCTextField();
        jCTextField28 = new app.bolivia.swing.JCTextField();
        jCTextField29 = new app.bolivia.swing.JCTextField();
        jCTextField30 = new app.bolivia.swing.JCTextField();
        jCTextField31 = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jCTextField1 = new app.bolivia.swing.JCTextField();
        jCTextField3 = new app.bolivia.swing.JCTextField();
        jCTextField4 = new app.bolivia.swing.JCTextField();
        jCTextField5 = new app.bolivia.swing.JCTextField();
        jCTextField6 = new app.bolivia.swing.JCTextField();
        jCTextField7 = new app.bolivia.swing.JCTextField();
        jCTextField8 = new app.bolivia.swing.JCTextField();
        jCTextField17 = new app.bolivia.swing.JCTextField();
        jPanel7 = new javax.swing.JPanel();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jCTextField19 = new app.bolivia.swing.JCTextField();
        jCTextField20 = new app.bolivia.swing.JCTextField();
        jCTextField25 = new app.bolivia.swing.JCTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jCTextField21 = new app.bolivia.swing.JCTextField();
        jCTextField22 = new app.bolivia.swing.JCTextField();
        jCTextField23 = new app.bolivia.swing.JCTextField();
        jCTextField24 = new app.bolivia.swing.JCTextField();
        jPanel9 = new javax.swing.JPanel();
        jCTextField9 = new app.bolivia.swing.JCTextField();
        jCTextField10 = new app.bolivia.swing.JCTextField();
        jCTextField11 = new app.bolivia.swing.JCTextField();
        jCTextField12 = new app.bolivia.swing.JCTextField();
        jCTextField13 = new app.bolivia.swing.JCTextField();
        jCTextField14 = new app.bolivia.swing.JCTextField();
        jCTextField15 = new app.bolivia.swing.JCTextField();
        jCTextField16 = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 70, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Western Conference");
        jPanel1.add(jLabel3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PLAYOFFS");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Eastern Conference");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField26ActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        jCTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField27ActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, -1));

        jCTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField28ActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 120, -1));

        jCTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField29ActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, -1));

        jCTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField30ActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, -1));

        jCTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField31ActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(350, 442));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(175, 442));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCTextField1.setText("jCTextField1");
        jPanel6.add(jCTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, -1));

        jCTextField3.setText("jCTextField1");
        jPanel6.add(jCTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, -1));

        jCTextField4.setText("jCTextField1");
        jPanel6.add(jCTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        jCTextField5.setText("jCTextField1");
        jPanel6.add(jCTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, -1));

        jCTextField6.setText("jCTextField1");
        jPanel6.add(jCTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));

        jCTextField7.setText("jCTextField1");
        jPanel6.add(jCTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, -1));

        jCTextField8.setText("jCTextField1");
        jPanel6.add(jCTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, -1));

        jCTextField17.setText("jCTextField1");
        jCTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField17ActionPerformed(evt);
            }
        });
        jPanel6.add(jCTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        jPanel4.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel7.setPreferredSize(new java.awt.Dimension(175, 442));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField2ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, -1));

        jCTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField19ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        jCTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField20ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, -1));

        jCTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField25ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, -1));

        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(350, 442));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(175, 442));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField21ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, -1));

        jCTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField22ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        jCTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField23ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, -1));

        jCTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField24ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 140, -1));

        jPanel5.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel9.setPreferredSize(new java.awt.Dimension(175, 442));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCTextField9.setText("jCTextField1");
        jPanel9.add(jCTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, -1));

        jCTextField10.setText("jCTextField1");
        jPanel9.add(jCTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, -1));

        jCTextField11.setText("jCTextField1");
        jPanel9.add(jCTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, -1));

        jCTextField12.setText("jCTextField1");
        jPanel9.add(jCTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));

        jCTextField13.setText("jCTextField1");
        jPanel9.add(jCTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, -1));

        jCTextField14.setText("jCTextField1");
        jPanel9.add(jCTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        jCTextField15.setText("jCTextField1");
        jPanel9.add(jCTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, -1));

        jCTextField16.setText("jCTextField1");
        jCTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField16ActionPerformed(evt);
            }
        });
        jPanel9.add(jCTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2ActionPerformed

    private void jCTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField16ActionPerformed

    private void jCTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField17ActionPerformed

    private void jCTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField19ActionPerformed

    private void jCTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField20ActionPerformed

    private void jCTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField21ActionPerformed

    private void jCTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField22ActionPerformed

    private void jCTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField23ActionPerformed

    private void jCTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField24ActionPerformed

    private void jCTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField25ActionPerformed

    private void jCTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField26ActionPerformed

    private void jCTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField27ActionPerformed

    private void jCTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField28ActionPerformed

    private void jCTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField29ActionPerformed

    private void jCTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField30ActionPerformed

    private void jCTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField31ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NBA_Bracket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NBA_Bracket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NBA_Bracket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NBA_Bracket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NBA_Bracket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextField1;
    private app.bolivia.swing.JCTextField jCTextField10;
    private app.bolivia.swing.JCTextField jCTextField11;
    private app.bolivia.swing.JCTextField jCTextField12;
    private app.bolivia.swing.JCTextField jCTextField13;
    private app.bolivia.swing.JCTextField jCTextField14;
    private app.bolivia.swing.JCTextField jCTextField15;
    private app.bolivia.swing.JCTextField jCTextField16;
    private app.bolivia.swing.JCTextField jCTextField17;
    private app.bolivia.swing.JCTextField jCTextField19;
    private app.bolivia.swing.JCTextField jCTextField2;
    private app.bolivia.swing.JCTextField jCTextField20;
    private app.bolivia.swing.JCTextField jCTextField21;
    private app.bolivia.swing.JCTextField jCTextField22;
    private app.bolivia.swing.JCTextField jCTextField23;
    private app.bolivia.swing.JCTextField jCTextField24;
    private app.bolivia.swing.JCTextField jCTextField25;
    private app.bolivia.swing.JCTextField jCTextField26;
    private app.bolivia.swing.JCTextField jCTextField27;
    private app.bolivia.swing.JCTextField jCTextField28;
    private app.bolivia.swing.JCTextField jCTextField29;
    private app.bolivia.swing.JCTextField jCTextField3;
    private app.bolivia.swing.JCTextField jCTextField30;
    private app.bolivia.swing.JCTextField jCTextField31;
    private app.bolivia.swing.JCTextField jCTextField4;
    private app.bolivia.swing.JCTextField jCTextField5;
    private app.bolivia.swing.JCTextField jCTextField6;
    private app.bolivia.swing.JCTextField jCTextField7;
    private app.bolivia.swing.JCTextField jCTextField8;
    private app.bolivia.swing.JCTextField jCTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
